#
# Makefile for RAtom program
# Zbigniew Romanowski [romz@wp.pl]
#


# Source files
SOURCE := $(wildcard *.cpp)
OBJECT = $(SOURCE:.cpp=.o)


all : $(OBJECT)


# Compiler based determination of dependencies - BEGIN
.depend: depend 


depend: $(SOURCE)
	rm -f ./.depend
	$(CXX) -E -MM $^ >> ./.depend;

include .depend
# Compiler based determination of dependencies - END



.cpp.o:
	$(CXX) $(CXXFLAGS) $(CXXINCL) -o $@ -c $<

clean:
	rm -f $(OBJECT) ./.depend 

